name: wohlrath_applied_scientist
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.13
  - numpy
  - pandas
  - ipykernel
  - scikit-learn
  - matplotlib
  - seaborn
  - tqdm
  - statsmodels
  - xgboost
  - scipy
  - pip
  - pip:
    - plotly
    - polars
    - python-dotenv
    - typer
    - loguru
    - -e .
